-- CREATING STAGING TABLES
CREATE TABLE AUX_FATO_VENDA(
	DATA_CARGA DATETIME NOT NULL,
	DATA_VENDA DATETIME NOT NULL,
	ID_VENDA INT NOT NULL,
	ID_ITEM INT NOT NULL,
	ID_SABOR INT NULL,
	ID_ESTABELECIMENTO INT NOT NULL,
	ID_LOCAL INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

CREATE TABLE VIO_FATO_VENDA(
	ID_VIOLACAO INT IDENTITY(1,1)NOT NULL PRIMARY KEY,
	DATA_CARGA DATETIME NOT NULL,
	DATA_VENDA DATETIME NOT NULL,
	ID_VENDA INT NOT NULL,
	ID_ITEM INT NOT NULL,
	ID_SABOR INT NULL,
	ID_ESTABELECIMENTO INT NOT NULL,
	ID_LOCAL INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	DATA_ERRO DATETIME NOT NULL,
	VIOLACAO VARCHAR NOT NULL,
)

CREATE TABLE AUX_SABOR(
	DATA_CARGA DATETIME NOT NULL,
	ID INT NOT NULL PRIMARY KEY,
	SABOR VARCHAR(30) NOT NULL
)

CREATE TABLE AUX_LOCAL(
	DATA_CARGA DATETIME NOT NULL,
	ID INT NOT NULL PRIMARY KEY,
	ESTADO CHAR(2) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL,
	RUA VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(8) NOT NULL
)

CREATE TABLE AUX_PRODUTO(
	DATA_CARGA DATETIME NOT NULL,
	ID INT NOT NULL PRIMARY KEY,
	PRODUTO VARCHAR(50) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

CREATE TABLE AUX_ESTABELECIMENTO(
	DATA_CARGA DATETIME NOT NULL,
	ID INT NOT NULL PRIMARY KEY,
	ID_LOCAL INT NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CNPJ VARCHAR(14) NULL
)

CREATE TABLE AUX_ITEM_ADICIONAL(
	DATA_CARGA DATETIME NOT NULL,
	ID_ITEM INT NOT NULL,
	ID_ADICIONAL INT NOT NULL,
)

CREATE TABLE AUX_ADICIONAL(
	DATA_CARGA DATETIME NOT NULL,
	ID INT NOT NULL PRIMARY KEY,
	ADICIONAL VARCHAR(30) NOT NULL,
	VALOR NUMERIC(10, 2) NOT NULL
)
