-- CREATING DIMENSION TABLES
CREATE TABLE FATO_VENDA(
	ID_VENDA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD_ITEM INT NOT NULL,
	ID_DATA_DA_VENDA BIGINT NOT NULL,
	ID_SABOR INT NULL,
	ID_GRUPO_ADICIONAIS INT NULL,
	ID_ESTABELECIMENTO INT NOT NULL,
	ID_LOCAL INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

CREATE TABLE DIM_SABOR(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	SABOR VARCHAR(30) NOT NULL
)

CREATE TABLE DIM_LOCAL(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL,
	RUA VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(8) NOT NULL
)

CREATE TABLE DIM_PRODUTO(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	PRODUTO VARCHAR(50) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	DATA_INICIO DATETIME NOT NULL,
	DATA_FIM DATETIME NULL,
	FL_CORRENTE VARCHAR(3) NOT NULL
)

CREATE TABLE DIM_ESTABELECIMENTO(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	COD_LOCAL INT NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CNPJ VARCHAR(14) NULL
)

CREATE TABLE DIM_GRUPO_ADICIONAL(
	ID INT NOT NULL PRIMARY KEY
)

CREATE TABLE BRIDGE_ADICIONAL(
	ID_GRUPO INT NOT NULL,
	ID_ADICIONAL INT NOT NULL
)

CREATE TABLE DIM_ADICIONAL(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	ADICIONAL VARCHAR(30) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	DATA_INICIO DATETIME NOT NULL,
	DATA_FIM DATETIME NULL,
	FL_CORRENTE VARCHAR(3) NOT NULL
)

CREATE TABLE DIM_TEMPO (
	ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NIVEL VARCHAR(8) NOT NULL CHECK (NIVEL IN ('DIA','MES','ANO')),
	DATA DATETIME NULL,
	DIA INT NULL,
	DIA_SEMANA VARCHAR(20) NULL,
	MES INT NULL,
	NOME_MES VARCHAR(20) NULL,
	TRIMESTRE INT NULL,
	NOME_TRIMESTRE VARCHAR(30) NULL,
	ANO INT NOT NULL
)

-- CREATING AGREGATTES
CREATE TABLE FATO_VENDA_LOCAL_MES(
	ID_MES BIGINT NOT NULL,
	ID_LOCAL INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR NUMERIC(10, 2) NOT NULL
)

-- CREATING INDEXES
CREATE INDEX IX_DIM_TEMPO_DATA_MES ON DIM_TEMPO (NIVEL, MES)
CREATE INDEX IX_DIM_TEMPO_DATA_ANO ON DIM_TEMPO (NIVEL, ANO)

-- REFERENTIAL INTEGRITY
ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_DW_VENDA_TEMPO
FOREIGN KEY(ID_DATA_DA_VENDA) REFERENCES DIM_TEMPO(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_DW_VENDA_SABOR
FOREIGN KEY(ID_SABOR) REFERENCES DIM_SABOR(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_DW_VENDA_LOCAL
FOREIGN KEY(ID_LOCAL) REFERENCES DIM_LOCAL(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_DW_VENDA_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES DIM_PRODUTO(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_DW_VENDA_ESTABELECIMENTO
FOREIGN KEY(ID_ESTABELECIMENTO) REFERENCES DIM_ESTABELECIMENTO(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_DW_VENDA_GRUPO_ADICIONAIS
FOREIGN KEY(ID_GRUPO_ADICIONAIS) REFERENCES DIM_GRUPO_ADICIONAL(ID)

ALTER TABLE BRIDGE_ADICIONAL
ADD CONSTRAINT FK_DW_BRIDGE_DIM_ADICIONAIS
FOREIGN KEY(ID_ADICIONAL) REFERENCES DIM_ADICIONAL(ID)

ALTER TABLE BRIDGE_ADICIONAL
ADD CONSTRAINT FK_DW_BRIDGE_DIM_GRUPO_ADICIONAIS
FOREIGN KEY(ID_GRUPO) REFERENCES DIM_GRUPO_ADICIONAL(ID)

ALTER TABLE DIM_ESTABELECIMENTO 
ADD CONSTRAINT FK_DW_ESTABELECIMENTO_LOCAL 
FOREIGN KEY (COD_LOCAL) REFERENCES DIM_LOCAL(ID)

ALTER TABLE FATO_VENDA_LOCAL_MES
ADD CONSTRAINT FK_DW_VENDA_LOCAL_MES_TEMPO
FOREIGN KEY(ID_MES) REFERENCES DIM_TEMPO(ID)

ALTER TABLE FATO_VENDA_LOCAL_MES
ADD CONSTRAINT FK_DW_VENDA_LOCAL_MES_LOCAL
FOREIGN KEY(ID_LOCAL) REFERENCES DIM_LOCAL(ID)

ALTER TABLE FATO_VENDA_LOCAL_MES
ADD CONSTRAINT FK_DW_VENDA_LOCAL_MES_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES DIM_PRODUTO(ID)
