use REDE_SORVETERIA

-- Qual o número de vendas hoje? 
SELECT SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
WHERE T.DATA = '20200101'

-- Qual o número de vendas nos últimos 2 meses? 
SELECT SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
WHERE T.DATA >= DATEADD(MONTH, -2, '20200101')

-- Qual o número de vendas por mês? 
SELECT T.MES, T.ANO, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
GROUP BY T.MES, T.ANO

-- Qual o número de vendas por estabelecimento?
SELECT E.NOME, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_ESTABELECIMENTO E ON(FV.ID_ESTABELECIMENTO = E.ID)
GROUP BY E.NOME

-- Qual o número de vendas por mês? Por estabelecimento?
SELECT T.MES, T.ANO, E.NOME, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
	JOIN DIM_ESTABELECIMENTO E ON(FV.ID_ESTABELECIMENTO = E.ID)
GROUP BY T.MES, T.ANO, E.NOME

-- Qual o rendimento por mês? Por estabelecimento?
SELECT T.MES, T.ANO, E.NOME, SUM(FV.VALOR) AS VALOR FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
	JOIN DIM_ESTABELECIMENTO E ON(FV.ID_ESTABELECIMENTO = E.ID)
GROUP BY T.MES, T.ANO, E.NOME

-- Qual o rendimento por produto? Por mês? Por estabelecimento?
SELECT T.MES, T.ANO, E.NOME, P.PRODUTO, SUM(FV.VALOR) AS VALOR FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
	JOIN DIM_ESTABELECIMENTO E ON(FV.ID_ESTABELECIMENTO = E.ID)
	JOIN DIM_PRODUTO P ON(FV.ID_PRODUTO = P.ID)
GROUP BY T.MES, T.ANO, E.NOME, P.PRODUTO

-- Qual o rendimento por produto?
SELECT P.PRODUTO, SUM(FV.VALOR) AS VALOR FROM FATO_VENDA FV
	JOIN DIM_PRODUTO P ON(FV.ID_PRODUTO = P.ID)
GROUP BY P.PRODUTO
ORDER BY SUM(FV.VALOR) DESC

-- Qual o rendimento por mês? 
SELECT T.MES, T.ANO, SUM(FV.VALOR) AS VALOR FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
GROUP BY T.MES, T.ANO

-- Qual o rendimento por estabelecimento? 
SELECT E.NOME, SUM(FV.VALOR) AS VALOR FROM FATO_VENDA FV
	JOIN DIM_ESTABELECIMENTO E ON(FV.ID_ESTABELECIMENTO = E.ID)
GROUP BY E.NOME
ORDER BY SUM(FV.VALOR) DESC

-- Qual o número de sorvetes vendidos por sabor? 
SELECT S.SABOR, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_PRODUTO P ON(FV.ID_PRODUTO = P.ID)
	JOIN DIM_SABOR S ON(S.ID = FV.ID_SABOR)
WHERE P.PRODUTO = 'BOLA DE SORVETE'
GROUP BY S.SABOR

-- Qual o número de sorvetes vendidos por mês? 
SELECT T.MES, T.ANO, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
	JOIN DIM_PRODUTO P ON(FV.ID_PRODUTO = P.ID)
WHERE P.PRODUTO = 'BOLA DE SORVETE'
GROUP BY T.MES, T.ANO

-- Qual o número de sorvetes vendidos por estabelecimento? 
SELECT E.NOME, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_ESTABELECIMENTO E ON(FV.ID_ESTABELECIMENTO = E.ID)
	JOIN DIM_PRODUTO P ON(FV.ID_PRODUTO = P.ID)
WHERE P.PRODUTO = 'BOLA DE SORVETE'
GROUP BY E.NOME
ORDER BY SUM(FV.QUANTIDADE) DESC


-- Qual o número de sorvetes vendidos por sabor? Por mês? 
SELECT T.MES, T.ANO, S.SABOR, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
	JOIN DIM_SABOR S ON(S.ID = FV.ID_SABOR)
	JOIN DIM_PRODUTO P ON(FV.ID_PRODUTO = P.ID)
WHERE P.PRODUTO = 'BOLA DE SORVETE'
GROUP BY T.MES, T.ANO, S.SABOR
ORDER BY T.MES, T.ANO

-- Qual o número de sorvetes vendidos por sabor? Por mês? Por estabelecimento?
SELECT  S.SABOR, T.MES, T.ANO, E.NOME, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T ON(FV.ID_DATA_DA_VENDA = T.ID)
	JOIN DIM_ESTABELECIMENTO E ON(FV.ID_ESTABELECIMENTO = E.ID)
	JOIN DIM_SABOR S ON(S.ID = FV.ID_SABOR)
	JOIN DIM_PRODUTO P ON(FV.ID_PRODUTO = P.ID)
WHERE P.PRODUTO = 'BOLA DE SORVETE'
GROUP BY S.SABOR, T.MES, T.ANO, E.NOME

-- Qual o número de picolés vendidos por sabor? Por mês?
SELECT T.MES, T.ANO, S.SABOR, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_PRODUTO P
	ON (P.ID = FV.ID_PRODUTO)
	JOIN DIM_SABOR S
	ON (FV.ID_SABOR = S.ID)
WHERE P.PRODUTO = 'PICOLÉ'
GROUP BY T.MES, T.ANO, S.SABOR
ORDER BY T.ANO, T.MES

-- Qual o número de picolés vendidos por sabor? Por mês? Por estabelecimento?
SELECT T.MES, T.ANO, S.SABOR, E.NOME, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_PRODUTO P
	ON (P.ID = FV.ID_PRODUTO)
	JOIN DIM_SABOR S
	ON (FV.ID_SABOR = S.ID)
	JOIN DIM_ESTABELECIMENTO E
	ON (E.ID = FV.ID_ESTABELECIMENTO)
WHERE P.PRODUTO = 'PICOLÉ'
GROUP BY T.MES, T.ANO, S.SABOR, E.NOME
ORDER BY T.ANO, T.MES

-- Qual o número de açaí vendidos por tamanho? Por mês?
SELECT T.MES, T.ANO, P.PRODUTO, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_PRODUTO P
	ON (P.ID = FV.ID_PRODUTO)
WHERE P.PRODUTO IN ('AÇAÍ G', 'AÇAÍ M', 'AÇAÍ P')
GROUP BY T.MES, T.ANO, P.PRODUTO
ORDER BY T.ANO, T.MES

-- Qual o número de açaí vendidos por tamanho? Por mês? Por estabelecimento?
SELECT T.MES, T.ANO, P.PRODUTO, E.NOME, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_PRODUTO P
	ON (P.ID = FV.ID_PRODUTO)
	JOIN DIM_ESTABELECIMENTO E
	ON (E.ID = FV.ID_ESTABELECIMENTO)
WHERE P.PRODUTO IN ('AÇAÍ G', 'AÇAÍ M', 'AÇAÍ P')
GROUP BY T.MES, T.ANO, P.PRODUTO, E.NOME
ORDER BY T.ANO, T.MES

-- Qual o número de sundae vendidos por sabor? Por mês?
SELECT T.MES, T.ANO, S.SABOR, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_PRODUTO P
	ON (P.ID = FV.ID_PRODUTO)
	JOIN DIM_SABOR S
	ON (FV.ID_SABOR = S.ID)
WHERE P.PRODUTO = 'SUNDAE'
GROUP BY T.MES, T.ANO, S.SABOR
ORDER BY T.ANO, T.MES

-- Qual o número de sundae vendidos por sabor? Por mês? Por estabelecimento?
SELECT T.MES, T.ANO, S.SABOR, E.NOME, SUM(FV.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_PRODUTO P
	ON (P.ID = FV.ID_PRODUTO)
	JOIN DIM_SABOR S
	ON (FV.ID_SABOR = S.ID)
	JOIN DIM_ESTABELECIMENTO E
	ON (E.ID = FV.ID_ESTABELECIMENTO)
WHERE P.PRODUTO = 'SUNDAE'
GROUP BY T.MES, T.ANO, S.SABOR, E.NOME
ORDER BY T.ANO, T.MES

-- Qual o número de adicionais vendidos por mês? Por estabelecimento?
SELECT T.MES, T.ANO, A.ADICIONAL, E.NOME, SUM(QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_GRUPO_ADICIONAL GA
	ON (GA.ID = FV.ID_GRUPO_ADICIONAIS)
	JOIN BRIDGE_ADICIONAL BA
	ON (BA.ID_GRUPO = GA.ID)
	JOIN DIM_ADICIONAL A
	ON (A.ID = BA.ID_ADICIONAL)
	JOIN DIM_ESTABELECIMENTO E
	ON (E.ID = FV.ID_ESTABELECIMENTO)
GROUP BY T.MES, T.ANO, A.ADICIONAL, E.NOME
ORDER BY T.ANO, T.MES

-- Qual o número de adicionais vendidos por açaí? Por mês? Por estabelecimento?
SELECT T.MES, T.ANO, A.ADICIONAL, P.PRODUTO, E.NOME, SUM(QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_PRODUTO P
	ON (P.ID = FV.ID_PRODUTO)
	JOIN DIM_GRUPO_ADICIONAL GA
	ON (GA.ID = FV.ID_GRUPO_ADICIONAIS)
	JOIN BRIDGE_ADICIONAL BA
	ON (BA.ID_GRUPO = GA.ID)
	JOIN DIM_ADICIONAL A
	ON (A.ID = BA.ID_ADICIONAL)
	JOIN DIM_ESTABELECIMENTO E
	ON (E.ID = FV.ID_ESTABELECIMENTO)
WHERE P.PRODUTO IN ('AÇAÍ G', 'AÇAÍ M', 'AÇAÍ P')
GROUP BY T.MES, T.ANO, A.ADICIONAL, P.PRODUTO, E.NOME
ORDER BY T.ANO, T.MES

-- Qual o número de adicionais vendidos por sundae? Por mês? Por estabelecimento?
SELECT T.MES, T.ANO, A.ADICIONAL, P.PRODUTO, E.NOME, SUM(QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA FV
	JOIN DIM_TEMPO T
	ON (T.ID = FV.ID_DATA_DA_VENDA)
	JOIN DIM_PRODUTO P
	ON (P.ID = FV.ID_PRODUTO)
	JOIN DIM_GRUPO_ADICIONAL GA
	ON (GA.ID = FV.ID_GRUPO_ADICIONAIS)
	JOIN BRIDGE_ADICIONAL BA
	ON (BA.ID_GRUPO = GA.ID)
	JOIN DIM_ADICIONAL A
	ON (A.ID = BA.ID_ADICIONAL)
	JOIN DIM_ESTABELECIMENTO E
	ON (E.ID = FV.ID_ESTABELECIMENTO)
WHERE P.PRODUTO = 'SUNDAE'
GROUP BY T.MES, T.ANO, A.ADICIONAL, P.PRODUTO, E.NOME
ORDER BY T.ANO, T.MES

-- Qual o número de vendas? Por produto? Por mês? Por cidade?
SELECT T.MES, T.ANO, P.PRODUTO, L.CIDADE, SUM(FVLM.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA_LOCAL_MES FVLM
	JOIN DIM_TEMPO T
	ON (T.ID = FVLM.ID_MES)
	JOIN DIM_PRODUTO P
	ON (P.ID = FVLM.ID_PRODUTO)
	JOIN DIM_LOCAL L
	ON (L.ID = FVLM.ID_LOCAL)
GROUP BY T.MES, T.ANO, P.PRODUTO, L.CIDADE
ORDER BY T.ANO, T.MES, L.CIDADE

-- Qual o número de vendas? Por produto? Por mês? Por estado?
SELECT T.MES, T.ANO, P.PRODUTO, L.ESTADO, SUM(FVLM.QUANTIDADE) AS QUANTIDADE FROM FATO_VENDA_LOCAL_MES FVLM
	JOIN DIM_TEMPO T
	ON (T.ID = FVLM.ID_MES)
	JOIN DIM_PRODUTO P
	ON (P.ID = FVLM.ID_PRODUTO)
	JOIN DIM_LOCAL L
	ON (L.ID = FVLM.ID_LOCAL)
GROUP BY T.MES, T.ANO, P.PRODUTO, L.ESTADO
ORDER BY T.ANO, T.MES, L.ESTADO

-- Qual o rendimento? Por produto? Por mês? Por estado?
SELECT T.MES, T.ANO, P.PRODUTO, L.ESTADO, SUM(FVLM.VALOR) AS QUANTIDADE FROM FATO_VENDA_LOCAL_MES FVLM
	JOIN DIM_TEMPO T
	ON (T.ID = FVLM.ID_MES)
	JOIN DIM_PRODUTO P
	ON (P.ID = FVLM.ID_PRODUTO)
	JOIN DIM_LOCAL L
	ON (L.ID = FVLM.ID_LOCAL)
GROUP BY T.MES, T.ANO, P.PRODUTO, L.ESTADO
ORDER BY T.ANO, T.MES, L.ESTADO

-- Qual o rendimento? Por produto? Por mês? Por cidade?
SELECT T.MES, T.ANO, P.PRODUTO, L.ESTADO, SUM(FVLM.VALOR) AS QUANTIDADE FROM FATO_VENDA_LOCAL_MES FVLM
	JOIN DIM_TEMPO T
	ON (T.ID = FVLM.ID_MES)
	JOIN DIM_PRODUTO P
	ON (P.ID = FVLM.ID_PRODUTO)
	JOIN DIM_LOCAL L
	ON (L.ID = FVLM.ID_LOCAL)
GROUP BY T.MES, T.ANO, P.PRODUTO, L.ESTADO
ORDER BY T.ANO, T.MES, L.ESTADO