USE REDE_SORVETERIA

CREATE TABLE TB_VENDA(
	ID INT NOT NULL PRIMARY KEY,
	ID_LOJA INT NOT NULL,
	VALOR DECIMAL(10, 2) NOT NULL,
	DATA_VENDA DATETIME
)

CREATE TABLE TB_LOJA(
	ID INT NOT NULL PRIMARY KEY,
	ID_LOCAL INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14),
)

CREATE TABLE TB_LOCAL(
	ID INT NOT NULL PRIMARY KEY,
	ESTADO CHAR(2) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(50),
	RUA VARCHAR(50),
	NUMERO VARCHAR(6)
)

CREATE TABLE TB_PRODUTO(
	ID INT NOT NULL PRIMARY KEY,
	PRODUTO VARCHAR(50) NOT NULL,
	VALOR DECIMAL(10, 2) NOT NULL,
)

CREATE TABLE TB_SABOR(
	ID INT NOT NULL PRIMARY KEY,
	SABOR VARCHAR(50) NOT NULL
)

CREATE TABLE TB_ADICIONAL(
	ID INT NOT NULL PRIMARY KEY,
	ADICIONAL VARCHAR(50) NOT NULL,
	VALOR DECIMAL(10, 2) NOT NULL
)

CREATE TABLE TB_ITEMADICIONAL(
	ID_ADICIONAL INT NOT NULL,
	ID_ITEM INT NOT NULL
)

CREATE TABLE TB_ITEM(
	ID INT NOT NULL PRIMARY KEY,
	ID_SABOR INT,
	ID_PRODUTO INT,
	ID_VENDA INT,
	VALOR DECIMAL(10, 2) NOT NULL
)

ALTER TABLE TB_VENDA
ADD CONSTRAINT FK_VENDA_LOJA
FOREIGN KEY(ID_LOJA) REFERENCES TB_LOJA(ID)

ALTER TABLE TB_LOJA
ADD CONSTRAINT FK_LOJA_LOCAL
FOREIGN KEY(ID_LOCAL) REFERENCES TB_LOCAL(ID)

ALTER TABLE TB_ITEMADICIONAL
ADD CONSTRAINT FK_ITEM_ADICIONAL
FOREIGN KEY(ID_ADICIONAL) REFERENCES TB_ADICIONAL(ID)

ALTER TABLE TB_ITEMADICIONAL
ADD CONSTRAINT FK_ADICIONAL_ITEM
FOREIGN KEY(ID_ITEM) REFERENCES TB_ITEM(ID)

ALTER TABLE TB_ITEM
ADD CONSTRAINT FK_ITEM_SABOR
FOREIGN KEY(ID_SABOR) REFERENCES TB_SABOR(ID)

ALTER TABLE TB_ITEM
ADD CONSTRAINT FK_ITEM_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTO(ID)

ALTER TABLE TB_ITEM
ADD CONSTRAINT FK_ITEM_VENDA
FOREIGN KEY(ID_VENDA) REFERENCES TB_VENDA(ID)


