CREATE TABLE FATO_VENDA(
	ID_VENDA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_TEMPO INT NOT NULL,
	ID_SABOR INT,
	ID_GRUPO_ADICIONAIS INT,
	ID_ESTABELECIMENTO INT NOT NULL,
	ID_LOCAL INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

CREATE TABLE DIM_SABOR(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	SABOR VARCHAR(30) NOT NULL
)

CREATE TABLE DIM_LOCAL(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL,
	RUA VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(8) NOT NULL
)

CREATE TABLE DIM_PRODUTO(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	PRODUTO VARCHAR(50) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

CREATE TABLE DIM_ESTABELECIMENTO(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	NOME VARCHAR(255),
	CNPJ VARCHAR(14)
)

CREATE TABLE DIM_GRUPO_ADICIONAIS(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
)

CREATE TABLE BRIDGE_ADICIONAIS(
	ID_GRUPO INT NOT NULL,
	ID_ADICIONAIS INT NOT NULL,
	PRIMARY KEY(ID_GRUPO, ID_ADICIONAIS)
)

CREATE TABLE DIM_ADICIONAIS(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD INT NOT NULL,
	ADICIONAL VARCHAR(30) NOT NULL
)

CREATE TABLE DIM_TEMPO (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NIVEL VARCHAR(8) NOT NULL CHECK (NIVEL IN ('DIA','MES','ANO')),
	DATA DATETIME NULL,
	DIA INT  NULL,
	DIA_SEMANA VARCHAR(20)  NULL,
	MES INT  NULL,
	NOME_MES VARCHAR(20)  NULL,
	TRIMESTRE INT  NULL,
	NOME_TRIMESTRE VARCHAR(30)  NULL,
	ANO INT NOT NULL
)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_VENDA_TEMPO
FOREIGN KEY(ID_TEMPO) REFERENCES DIM_TEMPO(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_VENDA_SABOR
FOREIGN KEY(ID_SABOR) REFERENCES DIM_SABOR(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_VENDA_LOCAL
FOREIGN KEY(ID_LOCAL) REFERENCES DIM_LOCAL(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_VENDA_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES DIM_PRODUTO(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_VENDA_ESTABELECIMENTO
FOREIGN KEY(ID_ESTABELECIMENTO) REFERENCES DIM_ESTABELECIMENTO(ID)

ALTER TABLE FATO_VENDA
ADD CONSTRAINT FK_VENDA_GRUPO_ADICIONAIS
FOREIGN KEY(ID_GRUPO_ADICIONAIS) REFERENCES DIM_GRUPO_ADICIONAIS(ID)

ALTER TABLE BRIDGE_ADICIONAIS
ADD CONSTRAINT FK_BRIDGE_DIM_ADICIONAIS
FOREIGN KEY(ID_ADICIONAIS) REFERENCES DIM_ADICIONAIS(ID)

ALTER TABLE BRIDGE_ADICIONAIS
ADD CONSTRAINT FK_BRIDGE_DIM_GRUPO_ADICIONAIS
FOREIGN KEY(ID_GRUPO) REFERENCES DIM_GRUPO_ADICIONAIS(ID)
