CREATE TABLE TB_AUX_FATO_VENDA(
	DATA_CARGA DATETIME NOT NULL,
	DATA_VENDA DATETIME NOT NULL,
	COD_VENDA INT NOT NULL,
	COD_TEMPO INT NOT NULL,
	COD_SABOR INT,
	COD_ESTABELECIMENTO INT NOT NULL,
	COD_LOCAL INT NOT NULL,
	COD_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

CREATE TABLE TB_VIO_FATO_VENDA(
	ID_VIOLACAO INT NOT NULL PRIMARY KEY,
	DATA_CARGA DATETIME NOT NULL,
	DATA_VENDA DATETIME NOT NULL,
	COD_VENDA INT NOT NULL,
	COD_TEMPO INT NOT NULL,
	COD_SABOR INT,
	COD_ESTABELECIMENTO INT NOT NULL,
	COD_LOCAL INT NOT NULL,
	COD_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	DATA_ERRO DATETIME NOT NULL,
	VIOLACAO VARCHAR NOT NULL,
)

CREATE TABLE TB_AUX_SABOR(
	DATA_CARGA DATETIME NOT NULL,
	COD_SABOR INT NOT NULL,
	SABOR VARCHAR(30) NOT NULL
)

CREATE TABLE TB_AUX_LOCAL(
	DATA_CARGA DATETIME NOT NULL,
	COD_LOCAL INT NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL,
	RUA VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(8) NOT NULL
)

CREATE TABLE TB_AUX_PRODUTO(
	DATA_CARGA DATETIME NOT NULL,
	COD_PRODUTO INT NOT NULL,
	PRODUTO VARCHAR(50) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

CREATE TABLE TB_AUX_ESTABELECIMENTO(
	DATA_CARGA DATETIME NOT NULL,
	COD_ESTABELECIMENTO INT NOT NULL,
	NOME VARCHAR(255),
	CNPJ VARCHAR(14)
)

CREATE TABLE TB_AUX_BRIDGE_ADICIONAL(
	DATA_CARGA DATETIME NOT NULL,
	COD_GRUPO INT NOT NULL,
	COD_ADICIONAL INT NOT NULL
)

CREATE TABLE TB_AUX_DIM_ADICIONAL(
	DATA_CARGA DATETIME NOT NULL,
	COD_ADICIONAL INT NOT NULL,
	ADICIONAL VARCHAR(30) NOT NULL
)