CREATE OR ALTER PROCEDURE SP_AGGREGATE_VENDA_LOCAL_MES
AS
BEGIN
    DECLARE @ID_MES BIGINT,
			@MES INT,
			@ANO INT,
			@ID_LOCAL INT,
			@ID_PRODUTO INT,
			@QUANTIDADE INT,
			@VALOR NUMERIC(10, 2),
			@ID_DIA BIGINT
	DECLARE C_MES CURSOR FOR 
		SELECT ID, MES, ANO FROM DIM_TEMPO WHERE NIVEL = 'MES' 

	DELETE FATO_VENDA_LOCAL_MES

	OPEN C_MES
	FETCH C_MES INTO @ID_MES, @MES, @ANO
	WHILE @@FETCH_STATUS = 0
	BEGIN
		INSERT INTO FATO_VENDA_LOCAL_MES
		SELECT @ID_MES, V.ID_LOCAL, V.ID_PRODUTO, SUM(V.QUANTIDADE), SUM(V.VALOR) 
		FROM FATO_VENDA V
		JOIN DIM_TEMPO T
		ON V.ID_DATA_DA_VENDA = T.ID
		WHERE MONTH(T.DATA) = @MES AND YEAR(T.DATA) = @ANO
		GROUP BY V.ID_LOCAL, V.ID_PRODUTO

		FETCH C_MES INTO @ID_MES, @MES, @ANO

	END
	CLOSE C_MES
	DEALLOCATE C_MES
END

GO

EXEC SP_AGGREGATE_VENDA_LOCAL_MES

DELETE FATO_VENDA_LOCAL_MES