USE REDE_SORVETERIA

CREATE TABLE TB_VENDA(
	id INT NOT NULL PRIMARY KEY,
	id_loja INT NOT NULL,
	valor DECIMAL(10, 2) NOT NULL,
	data_venda DATETIME
	FOREIGN KEY (id_loja) REFERENCES TB_LOJA(id),
)

CREATE TABLE TB_LOJA(
	id INT NOT NULL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	cnpj VARCHAR(14),
	id_local INT NOT NULL,
	FOREIGN KEY (id_local) REFERENCES TB_LOCAL(id)
)

CREATE TABLE TB_LOCAL(
	id INT NOT NULL PRIMARY KEY,
	estado CHAR(2) NOT NULL,
	cidade VARCHAR(50) NOT NULL,
	bairro VARCHAR(50),
	rua VARCHAR(50),
	numero VARCHAR(6)
)

CREATE TABLE TB_PRODUTO(
	id INT NOT NULL PRIMARY KEY,
	produto VARCHAR(50) NOT NULL,
	valor DECIMAL(10, 2) NOT NULL,
)

CREATE TABLE TB_SABOR(
	id INT NOT NULL PRIMARY KEY,
	sabor VARCHAR(50) NOT NULL
)

CREATE TABLE TB_ADICIONAL(
	id INT NOT NULL PRIMARY KEY,
	adicional VARCHAR(50) NOT NULL,
	valor DECIMAL(10, 2) NOT NULL,
)

CREATE TABLE TB_ITEMADICIONAL(
	id_adicional INT NOT NULL,
	id_item INT FOREIGN KEY REFERENCES TB_ITEM(id),
	FOREIGN KEY (id_adicional) REFERENCES TB_ADICIONAL(id),
)

CREATE TABLE TB_ITEM(
	id INT NOT NULL PRIMARY KEY,
	valor DECIMAL(10, 2) NOT NULL,
	id_sabor INT,
	id_produto INT,
	id_venda INT,
	FOREIGN KEY (id_sabor) REFERENCES TB_SABOR(id),
	FOREIGN KEY (id_produto) REFERENCES TB_PRODUTO(id),
	FOREIGN KEY (id_venda) REFERENCES TB_VENDA(id)
)
