-- BRIDGE ADICIONAL
CREATE SEQUENCE SQ_GRUPO_ADICIONAL START WITH 1 INCREMENT BY 1
GO
CREATE OR ALTER PROCEDURE SP_ETL_STAGING_TO_OLAP_BRIDGE_ADICIONAL
AS
BEGIN
	DECLARE @ID_ITEM INT

	DECLARE C_ITENS CURSOR FOR 
		SELECT DISTINCT ID_ITEM FROM AUX_ITEM_ADICIONAL

	OPEN C_ITENS
	FETCH C_ITENS INTO @ID_ITEM

	-- CURSOR FOR ITERATE ITEMS
	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT @ID_TEM
		FETCH C_ITENS INTO @ID_ITEM
	END

	CLOSE C_ITENS
	DEALLOCATE C_ITENS
END