-- ETL STAGING AREA TO OLAP
-- PRODUTO
GO
CREATE OR ALTER PROCEDURE SP_ETL_STAGING_TO_OLAP_PRODUTO(@DATA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @DATA_CARGA DATETIME, @ID_PRODUTO INT, @PRODUTO VARCHAR(50), @VALOR NUMERIC(10, 2)
	DECLARE @PRODUTO_TEMP VARCHAR(50), @VALOR_TEMP NUMERIC(10, 2)

	DECLARE C_PRODUTO CURSOR
	FOR SELECT P.DATA_CARGA, P.ID, P.PRODUTO, P.VALOR FROM AUX_PRODUTO P

	OPEN C_PRODUTO
	FETCH C_PRODUTO INTO @DATA_CARGA, @ID_PRODUTO, @PRODUTO, @VALOR

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- VERIFY IF THE PRODUCT NOT EXISTS IN THE OLAP THEN INSERT
		IF NOT EXISTS (SELECT * FROM DIM_PRODUTO WHERE COD = @ID_PRODUTO)
		BEGIN
			INSERT INTO DIM_PRODUTO(COD, PRODUTO, VALOR, DATA_INICIO, DATA_FIM, FL_CORRENTE)
			VALUES(@ID_PRODUTO, @PRODUTO, @VALOR, @DATA_CARGA, NULL, 'SIM')	
		END
		-- IF THE PRODUCT ALREADY EXISTS IN THE OLAP THEN 
		ELSE
		BEGIN
			-- GETTING THE OLDER VERSION OF PRODUCT
			SELECT @PRODUTO_TEMP = P.PRODUTO, @VALOR_TEMP = P.VALOR
			FROM DIM_PRODUTO P
			WHERE P.COD = @ID_PRODUTO AND P.FL_CORRENTE = 'SIM'

			-- VERIFY IF THE PRODUCT HAS CHANGED
			IF @PRODUTO_TEMP <> @PRODUTO OR @VALOR_TEMP <> @VALOR
			BEGIN
				-- UPDATE THE OLDER VERSION OF PRODUCT WITH THE END DATE AND FL_CORRENTE = 'NAO'
				UPDATE DIM_PRODUTO
				SET FL_CORRENTE = 'NAO', DATA_FIM = @DATA
				WHERE COD = @ID_PRODUTO AND FL_CORRENTE = 'SIM'

				-- INSERT THE NEW VERSION OF PRODUCT
				INSERT INTO DIM_PRODUTO(COD, PRODUTO, VALOR, DATA_INICIO, DATA_FIM, FL_CORRENTE)
				VALUES(@ID_PRODUTO, @PRODUTO, @VALOR, @DATA_CARGA, NULL, 'SIM')
			END
		END
		FETCH C_PRODUTO INTO @DATA_CARGA, @ID_PRODUTO, @PRODUTO, @VALOR
	END
	CLOSE C_PRODUTO
	DEALLOCATE C_PRODUTO
END

-- ADICIONAL
GO
CREATE OR ALTER PROCEDURE SP_ETL_STAGING_TO_OLAP_ADICIONAL(@DATA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @DATA_CARGA DATETIME, @ID_ADICIONAL INT, @ADICIONAL VARCHAR(50), @VALOR NUMERIC(10, 2)
	DECLARE @ADICIONAL_TEMP VARCHAR(50), @VALOR_TEMP NUMERIC(10, 2)

	DECLARE C_ADICIONAL CURSOR
	FOR SELECT A.DATA_CARGA, A.ID, A.ADICIONAL, A.VALOR FROM AUX_ADICIONAL A

	OPEN C_ADICIONAL
	FETCH C_ADICIONAL INTO @DATA_CARGA, @ID_ADICIONAL, @ADICIONAL, @VALOR

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- VERIFY IF THE ADICIONAL NOT EXISTS IN THE OLAP THEN INSERT
		IF NOT EXISTS (SELECT * FROM DIM_ADICIONAL WHERE COD = @ID_ADICIONAL)
		BEGIN
			INSERT INTO DIM_ADICIONAL(COD, ADICIONAL, VALOR, DATA_INICIO, DATA_FIM, FL_CORRENTE)
			VALUES(@ID_ADICIONAL, @ADICIONAL, @VALOR, @DATA_CARGA, NULL, 'SIM')	
		END
		-- IF THE ADICIONAL ALREADY EXISTS IN THE OLAP THEN 
		ELSE
		BEGIN
			-- GETTING THE OLDER VERSION OF ADICIONAL
			SELECT @ADICIONAL_TEMP = A.ADICIONAL, @VALOR_TEMP = A.VALOR
			FROM DIM_ADICIONAL A
			WHERE A.COD = @ID_ADICIONAL AND A.FL_CORRENTE = 'SIM'

			-- VERIFY IF THE ADICIONAL HAS CHANGED
			IF @ADICIONAL_TEMP <> @ADICIONAL OR @VALOR_TEMP <> @VALOR
			BEGIN
				-- UPDATE THE OLDER VERSION OF ADICIONAL WITH THE END DATE AND FL_CORRENTE = 'NAO'
				UPDATE DIM_ADICIONAL
				SET FL_CORRENTE = 'NAO', DATA_FIM = @DATA
				WHERE COD = @ID_ADICIONAL AND FL_CORRENTE = 'SIM'

				-- INSERT THE NEW VERSION OF ADICIONAL
				INSERT INTO DIM_ADICIONAL(COD, ADICIONAL, VALOR, DATA_INICIO, DATA_FIM, FL_CORRENTE)
				VALUES(@ID_ADICIONAL,@ADICIONAL, @VALOR, @DATA_CARGA, NULL, 'SIM')
			END
		END
		FETCH C_ADICIONAL INTO @DATA_CARGA, @ID_ADICIONAL, @ADICIONAL, @VALOR
	END
	CLOSE C_ADICIONAL
	DEALLOCATE C_ADICIONAL
END

-- SABOR
GO
CREATE OR ALTER PROCEDURE SP_ETL_STAGING_TO_OLAP_SABOR
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @ID_SABOR INT, @SABOR VARCHAR(30)

	DECLARE C_SABOR CURSOR
		FOR SELECT S.ID, S.SABOR FROM AUX_SABOR S

	OPEN C_SABOR
	FETCH C_SABOR INTO @ID_SABOR, @SABOR

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- VERIFY IF THE SABOR NOT EXISTS IN THE OLAP THEN INSERT
		IF NOT EXISTS (SELECT * FROM DIM_SABOR WHERE COD = @ID_SABOR )
		BEGIN
			INSERT INTO DIM_SABOR(COD, SABOR)
			VALUES(@ID_SABOR, @SABOR)
		END
		-- IF THE SABOR ALREADY EXISTS IN THE OLAP THEN UPDATE
		ELSE
		BEGIN
			UPDATE DIM_SABOR
			SET SABOR = @SABOR
			WHERE COD = @ID_SABOR 
		END
		FETCH C_SABOR INTO @ID_SABOR, @SABOR
	END
	CLOSE C_SABOR
	DEALLOCATE C_SABOR
END

-- LOCAL
GO
CREATE OR ALTER PROCEDURE SP_ETL_STAGING_TO_OLAP_LOCAL
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @ID_LOCAL INT, @ESTADO VARCHAR(2), @CIDADE VARCHAR(255), @BAIRRO VARCHAR(255), @RUA VARCHAR(255), @NUMERO VARCHAR(8)

	DECLARE C_LOCAL CURSOR
	FOR SELECT L.ID, L.ESTADO, L.CIDADE, L.BAIRRO, L.RUA, L.NUMERO FROM AUX_LOCAL L

	OPEN C_LOCAL
	FETCH C_LOCAL INTO @ID_LOCAL, @ESTADO, @CIDADE, @BAIRRO, @RUA, @NUMERO

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- VERIFY IF THE LOCAL NOT EXISTS IN THE OLAP THEN INSERT
		IF NOT EXISTS (SELECT * FROM DIM_LOCAL WHERE COD = @ID_LOCAL)
		BEGIN
			INSERT INTO DIM_LOCAL(COD, ESTADO, CIDADE, BAIRRO, RUA, NUMERO)
			VALUES(@ID_LOCAL, @ESTADO, @CIDADE, @BAIRRO, @RUA, @NUMERO)	
		END
		-- IF THE LOCAL ALREADY EXISTS IN THE OLAP THEN UPDATE
		ELSE
		BEGIN
			UPDATE DIM_LOCAL
			SET ESTADO = @ESTADO, 
				CIDADE = @CIDADE, 
				BAIRRO = @BAIRRO, 
				RUA = @RUA, 
				NUMERO = @NUMERO
			WHERE COD = @ID_LOCAL 
		END
		FETCH C_LOCAL INTO @ID_LOCAL, @ESTADO, @CIDADE, @BAIRRO, @RUA, @NUMERO
	END
	CLOSE C_LOCAL
	DEALLOCATE C_LOCAL
END

-- ESTABELECIMENTO
GO
CREATE OR ALTER PROCEDURE SP_ETL_STAGING_TO_OLAP_ESTABELECIMENTO
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @ID_ESTABELECIMENTO INT, @ID_LOCAL INT, @NOME VARCHAR(255), @CNPJ VARCHAR(14)

	DECLARE C_ESTABELECIMENTO CURSOR
		FOR SELECT E.ID, E.ID_LOCAL, E.NOME, E.CNPJ FROM AUX_ESTABELECIMENTO E

	OPEN C_ESTABELECIMENTO
	FETCH C_ESTABELECIMENTO INTO @ID_ESTABELECIMENTO, @ID_LOCAL, @NOME, @CNPJ

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- VERIFY IF THE ESTABELECIMENTO NOT EXISTS IN THE OLAP THEN INSERT
		IF NOT EXISTS (SELECT * FROM DIM_ESTABELECIMENTO WHERE COD = @ID_ESTABELECIMENTO)
		BEGIN
			INSERT INTO DIM_ESTABELECIMENTO(COD, COD_LOCAL, NOME, CNPJ)
			VALUES(@ID_ESTABELECIMENTO, @ID_LOCAL, @NOME, @CNPJ)	
		END
		-- IF THE ESTABELECIMENTO ALREADY EXISTS IN THE OLAP THEN UPDATE
		ELSE
		BEGIN
			UPDATE DIM_ESTABELECIMENTO
			SET NOME = @NOME, 
				CNPJ = @CNPJ
			WHERE COD = @ID_ESTABELECIMENTO 
		END
		FETCH C_ESTABELECIMENTO INTO @ID_ESTABELECIMENTO, @ID_LOCAL, @NOME, @CNPJ
	END
	CLOSE C_ESTABELECIMENTO
	DEALLOCATE C_ESTABELECIMENTO
END

-- FATO VENDA
GO
CREATE OR ALTER PROCEDURE SP_ETL_STAGING_TO_OLAP_FATO_VENDA
AS
BEGIN
	DECLARE @DATA_VENDA DATETIME, @ID_DATA_VENDA BIGINT, @COD_ITEM INT, @COD_PRODUTO INT, @COD_SABOR INT, @COD_ESTABELECIMENTO INT, @COD_LOCAL INT
	DECLARE @ID_SABOR INT, @ID_ESTABELECIMENTO INT, @ID_LOCAL INT, @ID_PRODUTO INT, @QUANTIDADE INT, @VALOR DECIMAL(10,2)
	DECLARE C_FATO_VENDA CURSOR FOR 
		SELECT DATA_VENDA, ID_ITEM, ID_SABOR, ID_ESTABELECIMENTO, ID_LOCAL, ID_PRODUTO, VALOR 
	FROM AUX_FATO_VENDA

	OPEN C_FATO_VENDA
	FETCH C_FATO_VENDA INTO @DATA_VENDA, @COD_ITEM, @COD_SABOR, @COD_ESTABELECIMENTO, @COD_LOCAL, @COD_PRODUTO, @VALOR
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @ID_DATA_VENDA = (SELECT ID FROM DIM_TEMPO T WHERE T.DATA = @DATA_VENDA)
		SET @ID_SABOR = (SELECT ID FROM DIM_SABOR S WHERE S.COD = @COD_SABOR)
		SET @ID_ESTABELECIMENTO = (SELECT ID FROM DIM_ESTABELECIMENTO E WHERE E.COD = @COD_ESTABELECIMENTO)
		SET @ID_LOCAL = (SELECT ID FROM DIM_LOCAL L WHERE L.COD = @COD_LOCAL)
		SET @ID_PRODUTO = (SELECT ID FROM DIM_PRODUTO P WHERE P.COD = @COD_PRODUTO)
		
		INSERT INTO FATO_VENDA(COD_ITEM, ID_DATA_DA_VENDA, ID_SABOR, ID_ESTABELECIMENTO, ID_LOCAL, ID_PRODUTO, QUANTIDADE, VALOR)
		VALUES(@COD_ITEM, @ID_DATA_VENDA, @ID_SABOR, @ID_ESTABELECIMENTO, @ID_LOCAL, @ID_PRODUTO, 1, @VALOR)

		FETCH C_FATO_VENDA INTO @DATA_VENDA, @COD_ITEM, @COD_SABOR, @COD_ESTABELECIMENTO, @COD_LOCAL, @COD_PRODUTO, @VALOR
	END
	CLOSE C_FATO_VENDA
	DEALLOCATE C_FATO_VENDA
END
GO

GO
CREATE OR ALTER PROCEDURE ETL_TODOS_PROCEDURE(@DATA DATETIME)
AS
BEGIN
	EXEC SP_ETL_STAGING_TO_OLAP_PRODUTO @DATA
	EXEC SP_ETL_STAGING_TO_OLAP_LOCAL
	EXEC SP_ETL_STAGING_TO_OLAP_ESTABELECIMENTO
	EXEC SP_ETL_STAGING_TO_OLAP_SABOR
	EXEC SP_ETL_STAGING_TO_OLAP_ADICIONAL @DATA
	EXEC SP_ETL_STAGING_TO_OLAP_FATO_VENDA
END

EXEC ETL_TODOS_PROCEDURE '2022-01-01'

SELECT * FROM FATO_VENDA
SELECT * FROM BRIDGE_ADICIONAL WHERE ID_GRUPO = 628
SELECT * FROM TB_ITEM_ADICIONAL WHERE ID_ITEM = 16649
-- DQL
DELETE FROM BRIDGE_ADICIONAL
DELETE FROM DIM_GRUPO_ADICIONAL
EXEC SP_ETL_STAGING_TO_OLAP_BRIDGE_ADICIONAL

SELECT * FROM DIM_GRUPO_ADICIONAL
SELECT * FROM DIM_PRODUTO
SELECT * FROM DIM_ADICIONAL

DELETE DIM_ESTABELECIMENTO
TRUNCATE TABLE DIM_LOCAL

EXEC SP_ETL_STAGING_TO_OLAP_ADICIONAL '2022-01-01'
EXEC SP_ETL_STAGING_TO_OLAP_LOCAL
EXEC SP_ETL_STAGING_TO_OLAP_ESTABELECIMENTO
EXEC SP_ETL_STAGING_TO_OLAP_FATO_VENDA
SELECT * FROM AUX_FATO_VENDA
SELECT * FROM DIM_ESTABELECIMENTO E JOIN DIM_LOCAL L ON (E.COD_LOCAL = L.COD)