CREATE TABLE DIM_TEMPO (
	ID_TEMPO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NIVEL VARCHAR(8) NOT NULL CHECK (NIVEL IN ('DIA','MES','ANO')),
	DATA DATETIME NULL,
	DIA INT  NULL,
	DIA_SEMANA VARCHAR(50)  NULL,
	MES INT  NULL,
	NOME_MES VARCHAR(100)  NULL,
	TRIMESTRE INT  NULL,
	NOME_TRIMESTRE VARCHAR(100)  NULL,
	ANO INT NOT NULL
)

CREATE INDEX IX_DIM_TEMPO_DATA_MES ON DIM_TEMPO (NIVEL, MES)
CREATE INDEX IX_DIM_TEMPO_DATA_ANO ON DIM_TEMPO (NIVEL, ANO)

GO
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO_DIA (@DT_INICIAL DATETIME, @DT_FINAL DATETIME)
AS
BEGIN
	DECLARE @DATA_ATUAL DATETIME,
		 @DAY_NUMBER INT,
		 @MES_NUM INT
	SET @DATA_ATUAL = @DT_INICIAL
	WHILE @DATA_ATUAL < @DT_FINAL
		BEGIN
			SET @MES_NUM = MONTH(@DATA_ATUAL)
			SET @DAY_NUMBER = DATEPART(dw,@DATA_ATUAL)
			--DEBUG
			--PRINT @DATA_ATUAL
			INSERT INTO DIM_TEMPO(NIVEL, DATA, DIA, DIA_SEMANA, MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, ANO)
			VALUES(
			'DIA',
			@DATA_ATUAL,
			DAY(@DATA_ATUAL),
			DATENAME(dw,@DATA_ATUAL),
			MONTH(@DATA_ATUAL),
			DATENAME(month,@DATA_ATUAL),
			(CASE 
				WHEN @MES_NUM in (1,2,3) THEN 1
				WHEN @MES_NUM in (4,5,6) THEN 2
				WHEN @MES_NUM in (7,8,9) THEN 3
				WHEN @MES_NUM in (10,11,12) THEN 4 END),

			(CASE 
				WHEN @MES_NUM in (1,2,3) THEN CONCAT('1º Trimestre / ', CONVERT(VARCHAR, YEAR(@DATA_ATUAL)))
				WHEN @MES_NUM in (4,5,6) THEN CONCAT('2º Trimestre / ', CONVERT(VARCHAR, YEAR(@DATA_ATUAL)))
				WHEN @MES_NUM in (7,8,9) THEN CONCAT('3º Trimestre / ', CONVERT(VARCHAR, YEAR(@DATA_ATUAL)))
				WHEN @MES_NUM in (10,11,12) THEN CONCAT('4º Trimestre / ', CONVERT(VARCHAR, YEAR(@DATA_ATUAL))) END),

			YEAR(@DATA_ATUAL)			
			)

			SET @DATA_ATUAL = DATEADD(DAY,1,@DATA_ATUAL)
		END

END
GO


GO
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO_MES (@DT_INICIAL DATETIME, @DT_FINAL DATETIME)
AS	
BEGIN
	DECLARE @DATA_ATUAL DATETIME
	DECLARE @MES_NUM INT
	SET @DATA_ATUAL = @DT_INICIAL
	WHILE @DATA_ATUAL < @DT_FINAL
		BEGIN
			SET @MES_NUM = MONTH(@DATA_ATUAL)
			--DEBUG
			--PRINT @DATA_ATUAL
			INSERT INTO DIM_TEMPO(NIVEL, MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, ANO)
			VALUES(
			'MES',
			MONTH(@DATA_ATUAL),
			DATENAME(month,@DATA_ATUAL),
			(CASE 
				WHEN @MES_NUM in (1,2,3) THEN 1
				WHEN @MES_NUM in (4,5,6) THEN 2
				WHEN @MES_NUM in (7,8,9) THEN 3
				WHEN @MES_NUM in (10,11,12) THEN 4 END),

			(CASE 
				WHEN @MES_NUM in (1,2,3) THEN CONCAT('1º Trimestre / ', CONVERT(VARCHAR, YEAR(@DATA_ATUAL)))
				WHEN @MES_NUM in (4,5,6) THEN CONCAT('2º Trimestre / ', CONVERT(VARCHAR, YEAR(@DATA_ATUAL)))
				WHEN @MES_NUM in (7,8,9) THEN CONCAT('3º Trimestre / ', CONVERT(VARCHAR, YEAR(@DATA_ATUAL)))
				WHEN @MES_NUM in (10,11,12) THEN CONCAT('4º Trimestre / ', CONVERT(VARCHAR, YEAR(@DATA_ATUAL))) END),

			YEAR(@DATA_ATUAL)			
			)

			SET @DATA_ATUAL = DATEADD(MONTH,1,@DATA_ATUAL)
		END
END
GO

GO
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO_ANO (@DT_INICIAL DATETIME, @DT_FINAL DATETIME)
AS	
BEGIN
	DECLARE @DATA_ATUAL DATETIME
	SET @DATA_ATUAL = @DT_INICIAL
	WHILE @DATA_ATUAL < @DT_FINAL
		BEGIN
			--DEBUG
			--PRINT @DATA_ATUAL
			INSERT INTO DIM_TEMPO(NIVEL, ANO)
			VALUES(
			'ANO',
			YEAR(@DATA_ATUAL)			
			)

			SET @DATA_ATUAL = DATEADD(YEAR,1,@DATA_ATUAL)
		END
END

GO
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO(@DT_INICIAL DATETIME, @DT_FINAL DATETIME)
AS
BEGIN
	EXEC SP_DIM_TEMPO_ANO @DT_INICIAL, @DT_FINAL
	EXEC SP_DIM_TEMPO_MES @DT_INICIAL, @DT_FINAL
	EXEC SP_DIM_TEMPO_DIA @DT_INICIAL, @DT_FINAL
END

EXEC SP_DIM_TEMPO '2022-01-01', '2023-02-01'

SELECT * FROM DIM_TEMPO

DELETE FROM DIM_TEMPO